### ISSUE TITLE
Automate JS build

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/mathplayground#115]
Right now the process is to commit compiled code into `media/mathplayground/build` to update the JS build. This is a basic process I put together years ago and haven't changed since. Is it time to finally sort out a way to reliably automate this via jenkins?

**Comment by nikolas** [comment]
I added `npm install` and `npm build` to the staging and prod jenkins build. That may be most of what's required here.

**Comment by nikolas** [comment]
Looks like there is more to do here to get it working - I'm still having to manually make the JS build myself and commit the compiled code to see the changes on production.

**Comment by drewyoungren** [comment]
On commit 3a416a3 I put (back) the functionality of npm run dev to watch the `media/mathplayground/build` folder, serve, and livereload it. I find this helpful for making small changes to the objects. I don't know if it interferes with the django end.

**Comment by nikolas** [comment]
The `npm run dev` shortcut we have configured on the main branch already watches and rebuilds for code changes, with rollup's `-w` flag: `"dev": "rollup -c -w",`.

This doesn't really have to do with the aim of this ticket - I'm trying to automate the production build on our continuous integration setup (Jenkins + our server infrastructure).

**Comment by nikolas** [comment]
I see what you're trying to do here though - a way to serve and make changes to the svelte app without starting up the django app. That's a use case I haven't considered, so we haven't put any time into making that work yet.
