### ISSUE TITLE
Save/Load scene state in room

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/mathplayground#121]
These are some general thoughts on the technical architecture of how we're going to handle shared scene state.

I'm realizing there's a new use case I want to handle that's not covered by the current websockets setup:

1. I enter a room and make an object on the graph
2. A different user enters the room after the new object is made

In this case, the second user didn't receive the websocket event, because they weren't on the page. Would it be crazy to store this state in a simple key-value store (Redis), somehow? Possibly. I mean, it could be a fine alternative to a database in this scenario as the ephemeral nature of the scene is fine: we are planning import/export functionality via csv.

We are using Redis for two things already in mathplayground:
* WebSockets channels communication
* Session storage

From my understanding, session storage is pretty much tied to a single user's client. It's a useful way to store data to a unique, anonymous user's client. I don't think it would really make sense to "share" session state between two different users... though the session mechanism may also prove useful here, somehow.

**Comment by Evan-CTL** [comment]
I would say that upon entering a room the user receives the current state of the presenter's scene. So it would query the presenter and receive the state data. I don't think that would require any storage. Though we might want to add a message queue so data isn't dropped, unless that feature is already built into websockets.

**Comment by nikolas** [comment]
Hmm - yeah, that's definitely one way to handle things. Only issue I can think of here is stability/data integrity, like you hinted at. Relying completely on a websockets message from a single client for the scene state just... feels like we may run into issues with 100 or so clients? Maybe not though, and it's def something to experiment with.

I think it would require some sort of handshake, as currently the "instructor" session doesn't send any messages to new "students". So, when a new client joins, send a message, only to "instructor" if possible, that I've joined - give me the state. Instructor sends the complete object state to student client.

**Comment by Evan-CTL** [comment]
That sounds right. And it might be good to add a User list that is updated when the professor receives the request for data. We can also send a notice when a user leaves to keep the user list up to date. That will also help to keep track how many responses have been received for a question vs how many people are in attendance.
