### ISSUE TITLE
Update svelte

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/mathplayground#142]
The svelte update is being held back by some accessibility checks, see: https://github.com/ccnmtl/mathplayground/actions/runs/3440572455/jobs/5739193274

It would be good to address these so we can stay on the latest version of svelte.

It's possible to put in special comments to ignore these errors, but we probably want to address these more directly - accessibility is one of our goals here after all.

**Comment by Evan-CTL** [comment]
Svelte has been updated
