### ISSUE TITLE
Flip Panel tab navigation

### ISSUE THREAD

**Issue by Evan-CTL** [ccnmtl/mathplayground#199]
There is more to do accessibility wise. I found a glaring issue with the “Flip Panel” functionality:

All elements are rendered in the order of their renderings in the Svelte apps. This does not change when they are hidden and they are not skipped over. Therefore to navigate to the object list you HAVE to tab through whatever chapter is open at the time. Hidden elements should not draw focus unless the element is supplemental to help with accessibility features.

**Comment by nikolas** [comment]
I think this has been addressed. We'll re-open if necessary.
