### ISSUE TITLE
LaTeX accessibility

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/mathplayground#26]
How can we make our math markup as accessible as possible? https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/math_role

**Comment by Evan-CTL** [comment]
Fails to render render dynamically for the math preview when building a poll. The initial render succeeds but if anything is typed into the text box it will break that MathJax element.

**Comment by nikolas** [comment]
Hmm, it looks like MathML is actually supported in Chrome, but it could absolutely be a related issue that KaTeX is failing on.

* https://developer.mozilla.org/en-US/docs/Web/MathML#browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/MathML/Examples
* e.g. this MathML example displays for me in all standard browsers: https://people.igalia.com/fwang/pell-bigint-mathml/

So, idk, maybe something to look into at some point, but definitely a low priority for now. We have MathJax working well enough for our purposes, but it's conceivable we could use MathML more directly in the future.
