### ISSUE TITLE
levelWorker is slow

### ISSUE THREAD

**Issue by drewyoungren** [ccnmtl/mathplayground#27]
Drawing level sets takes way too long, on the order of seconds. 

The culprit is likely `makeTraces` in [levelWorker.js](https://github.com/ccnmtl/mathplayground/blob/main/public/levelWorker.js) that it calls `marchingSquares` for every curve along each dimension, redundantly evaluating the function many times.

**Comment by nikolas** [comment]
levelWorker is now much faster - unfortunately deploying to our production environment (https://mathplayground.ctl.columbia.edu/) broke the WebWorker behavior - see my comment here (https://github.com/ccnmtl/mathplayground/issues/22#issuecomment-1289051548). So we'll be addressing that soon. It's still working in dev mode, and performs well.
