### ISSUE TITLE
All mathjs inputs: fail gracefully on invalid expression

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/mathplayground#296]
Show user error like red input field

**Comment by nikolas** [comment]
Svelte is causing our mathjs exceptions to not get properly caught, somehow: https://github.com/sveltejs/svelte/issues/7274

I'm investigating.

**Comment by nikolas** [comment]
Okay, this actually seems to be a mathjs quirk. In `Curve.updateCurve()`, the first error here is caught, but the second one isn't. Maybe mathjs's parse/compile flow is doing something asynchronous, changing contexts? I really can't imagine that.

```
+        try {                                                                                                                                                 
+            console.log(math.evaluate('asfoisjoi'));                                                                                                          
+        } catch (e) {                                                                                                                                         
+            console.error('woops!', e);                                                                                                                       
+        }                                                                                                                                                     
+                                                                                                                                                              
+        try {                                                                                                                                                 
+            goodParams['x'] = X.compile();                                                                                                                    
+        } catch (e) {                                                                                                                                         
+            console.error('compile error', e);                                                                                                                
+            return;                                                                                                                                           
+        } 
```

**Comment by Evan-CTL** [comment]
Does this still apply with the mathjs update that was pushed?

**Comment by nikolas** [comment]
Yeah. I think I've figured it out. We had a bunch of try/catch statements set to catch errors on any of mathjs's `parse` or `compile` functions, e.g. in Curve.svelte. Those would work, but the actual errors sometimes aren't thrown until the `evaluate` function is called, which is being used all throughout the rendering process. De-coupling this will be some manual work but do-able. I've got some basic error handling set up for the space curve, i'll open a PR in a second.

**Comment by drewyoungren** [comment]
It's true it's the `evaluate` method that is most important to check; this will catch parse errors as well.  I'm seeing a try/catch in the function passed to `ParametricGeometry` (commit 4e89ac4). That gets run a _lot_ and my instinct was to just do this once on a representative set of inputs when the user changes the parameter, but according to [this answer](https://stackoverflow.com/questions/19727905/in-javascript-is-it-expensive-to-use-try-catch-blocks-even-if-an-exception-is-n), there's no performance hit, so I guess there's no harm in being extra careful.

**Comment by nikolas** [comment]
This has been for the most part addressed with these changes: https://github.com/ccnmtl/mathplayground/pull/299

Next step, I'm going to methodically go through each object form from the UI side and just make sure this is in place for all inputs we expect and is working correctly.
