### ISSUE TITLE
Canvas focus

### ISSUE THREAD

**Issue by drewyoungren** [ccnmtl/mathplayground#307]
I'm getting an effect in recent builds where from the object list , when the "shade" is raised or lowered, it takes and extra click for the controls of the scene to respond, like it takes a click to "focus" on the canvas element. In limited testing, it doesn't seem to happen with the Chapters info box visible (raising or lowering takes no extra click), and doesn't seem to happen in older builds (I tried 26426df, at random).

**Comment by Evan-CTL** [comment]
Should be an easy fix. I'll set the focus to switch in the focus to canvas on any shade functions

**Comment by Evan-CTL** [comment]
https://github.com/ccnmtl/mathplayground/pull/312
