### ISSUE TITLE
"Chat socket closed unexpectedly"

### ISSUE THREAD

**Issue by Evan-CTL** [ccnmtl/mathplayground#324]
`Chat socket closed unexpectedly` this error keeps popping up on Firefox specifically, but looking at the django logs you can see that CONNECT is firing twice when a user makes or enters a room. Need to investigate. Nik suggests looking into the django-channels discussion boards. Look into async functions, race conditions, and possibly locks.

**Comment by Evan-CTL** [comment]
https://channels.readthedocs.io/en/stable/topics/consumers.html
https://docs.python.org/3/library/asyncio.html
https://redis.io/docs/manual/patterns/distributed-locks/

**Comment by nikolas** [comment]
I'm only seeing the CONNECT happening once when entering a room:
```
HTTP GET / 200 [0.02, 127.0.0.1:40114]
HTTP GET /media/mathplayground/build/bundle.js 200 [0.02, 127.0.0.1:40136]
HTTP GET /media/mathplayground/global.css 200 [0.03, 127.0.0.1:40122]
HTTP GET /media/mathplayground/build/bundle.css 200 [0.03, 127.0.0.1:40130]
HTTP GET /rooms/23/ 200 [0.01, 127.0.0.1:46184]
WebSocket HANDSHAKING /ws/rooms/23/ [127.0.0.1:46192]
WebSocket CONNECT /ws/rooms/23/ [127.0.0.1:46192]
```

I've set up the CONNECT to happen twice when making a room, intentionally. The is the socket is made, then setHost is called. Then, a new socket is made at the new URL route: https://github.com/ccnmtl/mathplayground/blob/main/media/src/modes/Session.svelte#L26

If there is an actual bug in how things work in this area, let's isolate that and focus on that.
