### ISSUE TITLE
Refresh deletes unpublished changes

### ISSUE THREAD

**Issue by Evan-CTL** [ccnmtl/mathplayground#384]
The way that a host connects to the room is the same as anyone else, which means that any adjustments made to the room that haven't been published are not preserved on refresh.

I think expected behavior for the local object list of every user would be to preserve on refresh, but overwrite all user lists in the room on publish. Thoughts?

**Comment by nikolas** [comment]
Unpublished changes aren't saved to the system at all - I would say this is expected behavior.
